project_name          = "url-shortener-saa"
env                   = "shared"
github_owner          = "Andropovbr"
github_repo           = "url-shortener-saa"
github_branch         = "main"
runtime_dev_state_key = "dev/runtime/terraform.tfstate"