name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Immutable image tag to promote (example: sha-55fb199)"
        required: true
        type: string

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4